config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/' => 'site#home'
  
   

  resources :events
  resources :visits
  resources :reservations

  namespace :admin do
    # resources :dashboard
    resources :dashboard
    resources :reservations 
    resources :events
    post 'reservations/accept/:id', to: 'reservations#accept'
    # get :events, to: 'dashboard#events'
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :date, presence: true

	mount_uploader :image, EventUploader

	def self.last_created_events(events) #Metodo de clase
		order(created_at: :desc).limit(events)
	end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	validates :email, :date, presence: true 

	enum state: {   wait:  0,
                	accept:  1,
                	cancel:   2 }
 
 	def self.last_created_reservation(reservation) #Metodo de clase
		order(created_at: :desc).limit(reservation)
	end


	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :username, uniqueness: true
  
end

app/models/visit.rb
class Visit < ActiveRecord::Base
	
	mount_uploader :image, EventUploader
	
	def self.last_created_visits(visits) #Metodo de clase
		order(created_at: :desc).limit(visits)
	end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

	def index
		@reservations = Reservation.all
		@visits = Visit.all 

		@visit = Visit.all.paginate(:page => params[:page], :per_page => 10)
		@reservation = Reservation.paginate(:page => params[:page], :per_page => 5)
		
		@events         = Event.all
		@calendar_items = ActiveModel::ArraySerializer \
			.new(@visits + @events,
           each_serializer: CalendarItemSerializer).to_json

		@onereservation = Reservation.new
	end

	def new
		@visit = Visit.new
		respond_to do |format|
			format.js
		end
	end
	
	def edit
		@visit = Visit.find params[:id]
	end
	def update
		@visit = Visit.find params[:id]
		if @visit.update_attributes visit_params 
			flash[:notice] = "Visit update successfully"
			redirect_to admin_dashboard_index_path
		end
	end

	def destroy
		@visit = Visit.find params[:id]
		@visit.destroy
			respond_to do |format|
				format.js
			end	
	end

	protected

	def visit_params 
 		params.require(:visit).permit(:title, :description, :date, :hours, :minutes, :turn, :members, :image)
	end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
	before_action :set_event, only: %i(edit show update destroy)

	def index
		@eventsindex = Event.all.paginate(:page => params[:page], :per_page => 5)
		@events = Event.all.to_json
		render layout: "admin"
	end

	def new
		@event = Event.new
		respond_to do |format|
			format.js
		end
	end

	def edit
	end

	def show
	end

	def create
		@event = Event.new events_params 
		if @event.save
			flash[:notice] = "Event create successfully"
			redirect_to admin_events_path
		else
			flash.now[:error] = "Error"
			render 'new'
		end
	end

	def update
		 if @event.update_attributes events_params 
		 	flash[:notice] = "Event update successfully"
		 	redirect_to admin_events_path
		 end
	end

	def destroy
		 @event.destroy
			respond_to do |format|
				format.js
			end
	end

  private

	def events_params 
 		params.require(:event).permit(:title, :description, :date, :image, :url, :members)
	end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/admin/reservations_controller.rb
require 'pry'
class Admin::ReservationsController < AdminController

	def accept
		@reservation = Reservation.find(params[:id])
		@reservation.accept!
		@reservation.save
		redirect_to admin_reservations_path
	end

	def index
		@reservation = Reservation.all.paginate(:page => params[:page], :per_page => 5)
	end

	def edit
		@reservation = Reservation.find params[:id]
		@prepend_form = [:admin, @reservation]
	end

	def update
		@reservation = Reservation.find params[:id]
		 if @reservation.update_attributes reservation_params 
		 	flash[:notice] = "Event update successfully"
		 	redirect_to admin_reservations_path
		 end
	end

	def destroy
		@reservation = Reservation.find params[:id]
		@reservation.destroy
			respond_to do |format|
				format.js
			end	
	end
	
	protected

	def reservation_params 
 		params.require(:reservation).permit(:title, :phone, :email, :members, :date, )
	end
	

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters,
            if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
	 	@reservation = Reservation.all
	# 	#puts @events.inspect
	end

	def new
		 @reservation = Reservation.new
	end

	def edit
		@reservation = Reservation.find params[:id]
		@prepend_form = [@reservation]
	end

	def create
		@reservation = Reservation.new reservation_params 
		if @reservation.save
			flash[:notice] = "Reservation create successfully, we will notify you within 24h"
			redirect_to "/"
		else
			flash.now[:error] = "Error"
			render 'new'
		end
	end

	def update
		@reservation = Reservation.find params[:id]
		if @reservation.update_attributes reservation_params 
			flash[:notice] = "Reservation update successfully"
			redirect_to "admin/dashboard"
		end
	end
	
	def reservation_params 
 		params.require(:reservation).permit(:title, :phone, :email, :members, :date, )
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
	    @visits         = Visit.all
	    @events         = Event.all
		
		@calendar_items = ActiveModel::ArraySerializer \
				.new(@visits + @events,
	           each_serializer: CalendarItemSerializer).to_json

		@reservation = Reservation.all
		@onereservation = Reservation.new
	end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
	def index
		@visits = Visit.all.to_json
		#puts @visits.inspect
	end

	def new
		 @visit = Visit.new
	end

	def show
		@visit = Visit.find params[:id]
	end

	def create
		@visit = Visit.new visit_params
		if @visit.save
			flash[:notice] = "Visit create successfully"
			redirect_to admin_dashboard_index_path	
		else
			flash.now[:error] = "Error"
			render 'new'
		end
	end

	def edit
		@visit = Visit.find params[:id]
	end

	def update
		@visit = Visit.find params[:id]
		if @visit.update_attributes visit_params 
			flash[:notice] = "Visit update successfully"
			redirect_to admin_dashboard_index_path
		end
	end

	def destroy
		@visit = Visit.find params[:id]
		if @visit.destroy
			flash[:notice] = "Visit destroy successfully"
			redirect_to admin_dashboard_index_path
		end
	end

	def visit_params 
 		params.require(:visit).permit(:title, :description, :date, :hours, :minutes, :turn, :members, :image)
	end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/admin/dashboard/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="myModalLabel">Visit new</h4>
    </div>
    <div class="modal-body">
     
        <%= render partial: 'new' %>
     
       <div class="img-visits-modal"></div><br> 
     
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/admin/dashboard/_new.html.erb
<%= form_for [@visit] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :turn %>
  <%= f.select :turn, options_for_select([['Morning', false],['Afternoon', true]]) %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :members %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br> 
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', '/' %>
 <% end %>

app/views/admin/dashboard/destroy.js.erb
$("#visit_" + <%= @visit.id %>).hide(1000)

app/views/admin/dashboard/edit.html.erb
<h1>Edit Visit</h1>
<%= form_for [@visit] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :turn %>
  <%= f.select :turn, options_for_select([['Morning', false],['Afternoon', true]], @visit.turn) %>
  <br>
   <%= f.label :members %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= image_tag @visit.image.url(:thumb) %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>

  <%= f.submit 'Save' %>

  <% end %>

app/views/admin/dashboard/index.html.erb
<div class="tables-area">
	<div class="tables-inline col-md-12">
		<table class="table table-hover table-condensed">
				<th> Image </th>
				<th> Title </th>
				<th> Description </th>
				<th> Edit </th>
			<% @visit.last_created_visits(5).each do |v| %>
			<tr id="visit_<%= v.id %>" >
				<td> <%= image_tag v.image.url(:thumb) %> </td>
				<td><%= v.title %> </td>
				<td><%= v.description.truncate(50) %></td>		
				<td><%= link_to 'Edit', edit_admin_dashboard_path(v.id) %></td>
				<td><%= link_to(admin_dashboard_path(v.id), method: :delete, remote: :true) do%>
				Delete
				<% end %>
				</td>
			<% end %>	
		</table>
	</div>

	<!-- <div class="tables-inline col-md-6">
		<table class="table table-hover table-condensed">
				<th> Title </th>
				<th> Description </th>
				<th> Edit </th>
			<div class="lists">Last reservation</div>
			<% @reservation.last_created_reservation(5).each do |r| %>
			<tr id="reservation_<%= r.id %>" >
				<td><%= r.title %> </td>
				<td><%= r.phone %> </td>
				<td><%= r.email %> </td>
				<td><%= link_to 'Edit', edit_admin_reservation_path(r.id) %> </td>
				</li>
			<% end %>
		</table>
	</div> -->
</div>
<div class="paginate apple_pagination col-md-12"><%= will_paginate @visit, :page_links => false %></div>

app/views/admin/dashboard/new.html.erb
 <h1>Visit new</h1>
<%= form_for [@visit] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :turn %>
  <%= f.select :turn, options_for_select([['Morning', false],['Afternoon', true]]) %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :members %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br> 
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', '/' %>
 <% end %>

app/views/admin/dashboard/new.js.erb
$('#myModal').html("<%= j(render partial: 'modal', locals: { visit: @visit }) %>");
$('#myModal').modal('show');

app/views/admin/dashboard/show.html.erb
<div class="area">
<div> Show event </div>

<%= @visit.title %>
<%= @visit.description %>
<button><%= link_to("Delete", visit_path(@visit), method: :delete, data: {confirm: 'Are you sure?'}) %></button>
</div>

app/views/admin/events/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="myModalLabel">Event new</h4>
    </div>
    <div class="modal-body">
     
        <%= render partial: 'new' %>
     
       <div class="img-visits-modal"></div><br> 
     
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/admin/events/_new.html.erb
<%= form_for [:admin, @event] do |f| %>

  <%= f.text_field :title, placeholder: 'Title' %>
  <br>

  <%= f.text_area :description, placeholder: 'Description' %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br> 
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>
  <%= f.label :members %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date, required: true %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', '/' %>
 <% end %>

app/views/admin/events/destroy.js.erb
$("#event_" + <%= @event.id %>).hide(1000)

app/views/admin/events/edit.html.erb
<h1>Edit Events</h1>
<%= form_for [:admin, @event] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= image_tag @event.image.url(:thumb) %>
  <br> 
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>
  <%= f.label :members %>
  <%= f.text_field :members %>
 <!--  <br>
  <%= f.label :turn %>
  <%= f.select :turn, options_for_select([['Morning', false],['Afternoon', true]], @event.turn) %> -->
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>

  <%= f.submit 'Save' %>

  <% end %>

app/views/admin/events/index.html.erb
	<table class="table table-hover table-condensed">
		<th> Image </th>
		<th> Title </th>
		<th> Description </th>
		<th> Url Event </th>
		<th> </th>
		<th> </th>
		
		<% @eventsindex.last_created_events(5).each do |e| %>
		<tr id="event_<%= e.id %>" >
			<td> <%= image_tag e.image.url(:thumb) %> </td>
			<td> <%= e.title %> </td>
			<td> <%= e.description.truncate(10) %> </td>
			<td> <a href="<%= e.url %>"> Link </a> </td>
			
			<td><button class="buttons_admin btn btn-warning"><%= link_to 'Edit', edit_admin_event_path(e.id)%></button></td>
			<td><button class="buttons_admin btn btn-danger"><%= link_to(admin_event_path(e.id), method: :delete, remote: :true) do %>
			Delete
			<% end %></button></td>	
		</tr>
		<% end %>
		
	</table>
<div class="paginate apple_pagination "><%= will_paginate @eventsindex %></div>

app/views/admin/events/new.html.erb
 <h1>Event new</h1>

<%= form_for [:admin, @event] do |f| %>

  <%= f.text_field :title, placeholder: 'Title' %>
  <br>

  <%= f.text_area :description, placeholder: 'Description' %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br> 
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>
  <%= f.label :members %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date, required: true %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', '/' %>
 <% end %>

app/views/admin/events/new.js.erb
$('#myModal').html("<%= j(render partial: 'modal', locals: { event: @event }) %>");
$('#myModal').modal('show');

app/views/admin/events/show.html.erb
<%= debug(@event) %>

app/views/admin/reservations/destroy.js.erb
$("#reservation_" + <%= @reservation.id %>).hide()

app/views/admin/reservations/edit.html.erb
<h1>Edit Reservations</h1>
<%= form_for @prepend_form do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br>
  <%= f.label :email  %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :members  %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :date  %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit 'Save' %>

  <% end %>

app/views/admin/reservations/index.html.erb
<table class="table table-hover table-condensed wait">WAIT
<th> Title </th>
<th> Email </th>
<th> Phone </th>
<th> Members </th>
<th> Date </th>
<th> State </th>
<th>  </th>
<th>  </th>
<th>  </th>
<% @reservation.last_created_reservation(5).each do |r| %>
<tr id="reservation_<%= r.id %>" >
	<% if r.state == "wait" %>
	<td> <%= r.title %> </td>
	<td><%= r.email %> </td>
	<td> <%= r.phone %> </td>
	<td> <%= r.members %> </td>
	<td> <%= r.date %> </td>
	<td> <%= r.state %> </td>
	<td><%= button_to 'Accept',admin_path(r.id), method: :post, :class => 'btn btn-success' %></td>
	<td><%= button_to(admin_reservation_path(r.id), method: :delete, remote: true, :class => 'btn btn-danger') do %>
		Delete
	<% end %></td>
	<td><%= button_to 'Edit', edit_admin_reservation_path(r.id), :class => 'btn btn-warning' %></td>
	<% end %>
</tr>
<% end %>
</table>

<table class="table table-hover table-condensed accept"> ACCEPT
<th> Title </th>
<th> Email </th>
<th> Phone </th>
<th> Members </th>
<th> Date </th>
<th> State </th>
<th>  </th>
<th>  </th>
<% @reservation.last_created_reservation(5).each do |r| %>
<tr>
	<% if r.state == "accept" %>
	<td> <%= r.title %> </td>
	<td><%= r.email %> </td>
	<td> <%= r.phone %> </td>
	<td> <%= r.members %> </td>
	<td> <%= r.date %> </td>
	<td> <%= r.state %> </td>

	
	<td><button class="buttons_admin btn btn-warning"><%= link_to 'Edit', edit_admin_reservation_path(r.id)%></button></td>
	<% end %>
</tr>
<% end %>
</table>
<div class="paginate apple_pagination "><%= will_paginate @reservation %></div>

app/views/admin/reservations/update.js.erb
alert('asdasd');

app/views/events/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="myModalLabel"><%= event.title %></h4>
    </div>
    <div class="modal-body">
      <div class="img-events-modal"><%= image_tag event.image.url(:thumb) %></div><br>
      <div>
    <!--   <% if event.image.present? %>
        <%= image_tag event.image.url(:thumb) %>
      <% end %> -->

      <%= event.description %></div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/events/new.html.erb
 <h1>Event new</h1>
<%= form_for [@event] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', '/' %>
 <% end %>

app/views/events/show.html.erb
<div class="area">
<div> Show event </div>

<%= @event.title %>
<%= @event.description %>
<button><%= link_to("Delete", event_path(@event), method: :delete, data: {confirm: 'Are you sure?'}) %></button>
</div>

app/views/events/show.js.erb
$('#myModal').html("<%= j(render partial: 'modal', locals: { event: @event }) %>");
$('#myModal').modal('show');

app/views/reservations/_new.html.erb
<%= form_for [@onereservation] do |f| %>
  
  <%= f.text_field :title, :placeholder => "Title", required: true %>
  <br>
  
  <%= f.text_field :phone, :placeholder => "Phone" %>
  <br>
  
  <%= f.text_field :email, :placeholder => "email", required: true%>
  <br>
  
  <%= f.text_field :members, :placeholder => "members" %>
  <br>
  
  <%= f.date_field :date, :placeholder => "date", required: true %>
  <br>
  <%= f.submit 'Save', :class => 'submit_class_reservation_home' %>

  <% end %>

app/views/reservations/index.html.erb
<% @reservation.each do |r| %>
<li>
	<%= r.title %>
	<%= r.email %>
	<%= r.phone %>
	<%= r.members %>
	<%= r.state %>
	<%= r.date %>
<Li>
<% end %>

app/views/reservations/new.html.erb
<h1>Reservation</h1>
<%= form_for [@reservation] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <br>
  <%= f.label :email  %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :members  %>
  <%= f.text_field :members %>
  <br>
  <%= f.label :date  %>
  <%= f.date_field :date %>
  <br>
  <%= f.submit 'Save' %>

  <% end %>

app/views/site/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>

</head>
<header>
	
</header>
<body>
<section class="row">
	<article class="center">

		<div class="flash bg-success"><%= flash[:notice] %></div>
		<div class="flash bg-danger"><%= flash[:error] %></div>

		<div id="calendar" class="col-md-9 col-xs-12 col-ls-9">
			<%= javascript_tag do -%>
				var visits = <%= @calendar_items.html_safe %>;
			<% end -%>
		</div>
		<div class="list-visits col-md-3">
			<!-- <div class="eventclick"></div>  -->

			<button class="btn btn-success button-event">Last Events</button>

			<div class="render-last-events">
				<%if @events.present? %>
					<% @events.last_created_events(3).each do |e| %>
						<div class="list-title"><%= e.title %></div>
						<div class="list-description"><%= e.description.truncate(40) %></div>
						<div class="list-image"><%= image_tag e.image.url(:thumb) %></div>
						<div class="list-url"> <a target="_blank" href="<%= e.url %>">Link Event</a></div>
						<hr>
					<% end %>
					<% else %>
						No events
				<% end %>
			</div>

			<button class="btn btn-info button-visit">Last Visit</button>
			
			<div class="render-last-visit">
					<% @visits.last_created_visits(5).each do |v| %>
						<div class="list-title"><%= v.title %></div>
						<div class="list-members">Members: <%= v.members %></div>
						<div class="list-description"><%= v.date %></li></div><hr>
					<% end %>
			</div>

			<button class="btn btn-primary button-reservation">Reservation</button>

			<div class="render-reservation">
				<%= render partial: 'reservations/new' %>
			</div>
		</div>
	</section>
	</article>
	
</body>

</html>

app/views/visits/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4 class="modal-title" id="myModalLabel"><%= visit.title %></h4>
    </div>
    <div class="modal-body">
      
       <div class="img-visits-modal"><%= image_tag visit.image.url(:thumb) %></div><br> 
      <%= visit.description %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/visits/show.html.erb
<div class="area">
<div> Show event </div>

<%= @visit.title %>
<%= @visit.description %>
<button><%= link_to("Delete", visit_path(@visit), method: :delete, data: {confirm: 'Are you sure?'}) %></button>
</div>

app/views/visits/show.js.erb
$('#myModal').html("<%= j(render partial: 'modal', locals: { visit: @visit }) %>");
$('#myModal').modal('show');