config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/' => 'site#home'
  
   

  resources :events
  resources :visits
  resources :reservations

  namespace :admin do
    # resources :dashboard
    resources :dashboard
    resources :reservations 
    resources :events
    post 'reservations/accept/:id', to: 'reservations#accept'
    # get :events, to: 'dashboard#events'
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :date, presence: true

	mount_uploader :image, EventUploader

	def self.last_created_events(events) #Metodo de clase
		order(created_at: :desc).limit(events)
	end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	validates :email, :date, presence: true 

	enum state: {   wait:  0,
                	accept:  1,
                	cancel:   2 }
 
 	def self.last_created_reservation(reservation) #Metodo de clase
		order(created_at: :desc).limit(reservation)
	end


	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :username, uniqueness: true
  
end

app/models/visit.rb
class Visit < ActiveRecord::Base
	
	mount_uploader :image, EventUploader
	
	def self.last_created_visits(visits) #Metodo de clase
		order(created_at: :desc).limit(visits)
	end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
	before_action :set_event, only: %i(edit show update destroy)

	def index
		@eventsindex = Event.all.paginate(:page => params[:page], :per_page => 5)
		@events = Event.all.to_json
		render layout: "admin"
	end

	def new
		@event = Event.new
		respond_to do |format|
			format.js
		end
	end

	def edit
	end

	def show
	end

	def create
		@event = Event.new events_params 
		if @event.save
			flash[:notice] = "Event create successfully"
			redirect_to admin_events_path
		else
			flash.now[:error] = "Error"
			render 'new'
		end
	end

	def update
		 if @event.update_attributes events_params 
		 	flash[:notice] = "Event update successfully"
		 	redirect_to admin_events_path
		 end
	end

	def destroy
		 @event.destroy
			respond_to do |format|
				format.js
			end
	end

  private

	def events_params 
 		params.require(:event).permit(:title, :description, :date, :image, :url, :members)
	end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters,
            if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def show
		@event = Event.find(params[:id])
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
	 	@reservation = Reservation.all
	# 	#puts @events.inspect
	end

	def new
		 @reservation = Reservation.new
	end

	def edit
		@reservation = Reservation.find params[:id]
		@prepend_form = [@reservation]
	end

	def create
		@reservation = Reservation.new reservation_params 
		if @reservation.save
			flash[:notice] = "Reservation create successfully, we will notify you within 24h"
			redirect_to "/"
		else
			flash.now[:error] = "Error"
			render 'new'
		end
	end

	def update
		@reservation = Reservation.find params[:id]
		if @reservation.update_attributes reservation_params 
			flash[:notice] = "Reservation update successfully"
			redirect_to "admin/dashboard"
		end
	end
	
	def reservation_params 
 		params.require(:reservation).permit(:title, :phone, :email, :members, :date, )
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home
	    @visits         = Visit.all
	    @events         = Event.all
		
		@calendar_items = ActiveModel::ArraySerializer \
				.new(@visits + @events,
	           each_serializer: CalendarItemSerializer).to_json

		@reservation = Reservation.all
		@onereservation = Reservation.new
	end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
	def index
		@visits = Visit.all.to_json
		#puts @visits.inspect
	end

	def new
		 @visit = Visit.new
	end

	def show
		@visit = Visit.find params[:id]
	end

	def create
		@visit = Visit.new visit_params
		if @visit.save
			flash[:notice] = "Visit create successfully"
			redirect_to admin_dashboard_index_path	
		else
			flash.now[:error] = "Error"
			render 'new'
		end
	end

	def edit
		@visit = Visit.find params[:id]
	end

	def update
		@visit = Visit.find params[:id]
		if @visit.update_attributes visit_params 
			flash[:notice] = "Visit update successfully"
			redirect_to admin_dashboard_index_path
		end
	end

	def destroy
		@visit = Visit.find params[:id]
		if @visit.destroy
			flash[:notice] = "Visit destroy successfully"
			redirect_to admin_dashboard_index_path
		end
	end

	def visit_params 
 		params.require(:visit).permit(:title, :description, :date, :hours, :minutes, :turn, :members, :image)
	end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Administration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<div class="header">
	<div class="logo">
	Book a <span class="visit">Visit</span>
	</div>
	
	<div class="login">
		<% if user_signed_in? %>
		<%= link_to 'Home', "/" %>
		<%= link_to 'Visits', admin_dashboard_index_path %>
		<%= link_to 'Events', admin_events_path %>	
		<%= link_to 'Reservations', admin_reservations_path %>
		<%= link_to 'Add Visit', new_admin_dashboard_path, remote: true%>
		<%= link_to 'Add Event', new_admin_event_path, remote: true %>
		<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,
			data: { confirm: 'Are you sure?' } %>
		<% else %>
		<%= link_to 'Sign In', new_user_session_path %>
		<% end %>
	</div>
</div>
<div class="area">
<%= yield %>
</div>
<footer class="footer col-md-12 col-xs-12 col-ls-12">
		<%= link_to 'Admin', admin_dashboard_index_path %> Ironhack 2014 - Layout Admin
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Museum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<div class="header">
	<div class="logo">
	Book a <span class="visit">Visit</span>
	</div>
	
	<div class="login">
		<% if user_signed_in? %>
		<%= link_to 'Home', "/" %>
		<%= link_to 'Visits', admin_dashboard_index_path %>
		<%= link_to 'Events', admin_events_path %>	
		<%= link_to 'Reservations', admin_reservations_path %>
		<%= link_to 'Add Visit', new_admin_dashboard_path, remote: true %>
		<%= link_to 'Add Event', new_admin_event_path, remote: true %>
		<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,
			data: { confirm: 'Are you sure?' } %>
		<% else %>
		<%= link_to 'Sign In', new_user_session_path %>
		<% end %>
	</div>
</div>

<div class="area">
		<%= yield %>
</div>

<footer class="footer">
		<%= link_to 'Admin', admin_dashboard_index_path %> Ironhack 2014
</footer>
</body>
</html>